# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5223e87c8af55827a2bdca7b349cc925242ebfc26a5060b2c5c20893167c844f4b121c7224bf918ec593e245e62c76ac982cc8f0e9f078e181b840983359e82

test:
  secret_key_base: 5042bef51e82bd52cc93e2812e045c1e603156e2d117ad16dee291d6fefd729dceeb96b69260c1b0cae612537e346aa59fad5e8fbe8e816f31b22ff1a04953a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
